ALTER TABLE scans ADD COLUMN IF NOT EXISTS slice_count INT NOT NULL DEFAULT 1;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS slice_filenames_json TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS study_hash VARCHAR(64);
ALTER TABLE scans ADD COLUMN IF NOT EXISTS is_escalated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS triage_json TEXT;
ALTER TABLE scans ADD COLUMN IF NOT EXISTS reviewer_name VARCHAR(255);
ALTER TABLE scans ADD COLUMN IF NOT EXISTS reviewer_credentials VARCHAR(255);
ALTER TABLE scans ADD COLUMN IF NOT EXISTS sign_off_notes TEXT;

CREATE INDEX IF NOT EXISTS idx_scans_user_study_hash ON scans(user_id, study_hash);
