import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

Future<String> savePdfAndOpen(List<int> bytes, String filename) async {
  // Save to application documents directory so file persists beyond temporary cache
  Directory dir;
  try {
    dir = await getApplicationDocumentsDirectory();
  } catch (_) {
    dir = await getTemporaryDirectory();
  }

  final file = File('${dir.path}/$filename');
  await file.writeAsBytes(bytes, flush: true);

  // Use share_plus with XFile which uses Android FileProvider (content:// URI)
  // to avoid FileUriExposedException and Android scoped storage access errors
  final xFile = XFile(
    file.path,
    mimeType: 'application/pdf',
    name: filename,
  );

  await SharePlus.instance.share(
    ShareParams(
      files: [xFile],
      subject: 'Lucidia Radiology Report - $filename',
      text: 'Radiology Report PDF generated by Lucidia (assistive second-read decision support).',
    ),
  );

  return file.path;
}
